---

- hosts: localhost
  connection: local
  tasks:
    - stat: path=./ansible_tdd.yml
      register: ansible_tdd_config
    - name: Create Provisioning template
      copy: src=templates/ansible_tdd.yml dest=./ansible_tdd.yml
      when: not ansible_tdd_config.stat.exists

    - stat: path=./.gitignore
      register: gitignore_config
    - name: Create gitignore
      copy: src=templates/gitignore dest=./.gitignore
      when: not gitignore_config.stat.exists

    - name: Creates test directory
      file: path=test/ansible-tdd/intergration/suite-name state=directory recurse=true

    - stat: path=./test/ansible-tdd/intergration/suite-name/suite-playbook-default.yml
      register: suite_playbook_default_config
    - name: Create sample file playbook
      copy: src=templates/suite-playbook-default.yml dest=./test/ansible-tdd/intergration/suite-name
      when: not suite_playbook_default_config.stat.exists