---

- hosts: localhost
  connection: local
  tasks:
    - name: Creates log directory for ansible tdd
      file: path=./.log state=directory recurse=true
    - stat: path=./.log/README.markdown
      register: readme_markdown
    - name: Generate Readme markdown
      copy: content="All temporary files when ansible tdd run, it will generate at here" dest=./.log/README.markdown
      when: not readme_markdown.stat.exists

    - stat: path=./ansible_tdd.yml
      register: ansible_tdd_config
    - name: Create Provisioning template
      copy: src=templates/ansible_tdd.yml dest=./ansible_tdd.yml
      when: not ansible_tdd_config.stat.exists

    - stat: path=./.rspec
      register: rspec_config
    - name: rspec template
      copy: src=templates/serverspec/.rspec dest=./.rspec
      when: not rspec_config.stat.exists

    - stat: path=./.gitignore
      register: gitignore_config
    - name: Create gitignore
      copy: src=templates/gitignore dest=./.gitignore
      when: not gitignore_config.stat.exists

    - stat: path=./vault_ec2_secret_access.yml
      register: vault_ec2_secret_access
    - name: Create vault ec2
      copy: src=templates/vault_ec2_secret_access.yml dest=./vault_ec2_secret_access.yml
      when: not vault_ec2_secret_access.stat.exists

    - stat: path=./.vault_pass.txt
      register: vault_pass
    - name: Create vault password
      copy: src=templates/vault_pass.txt dest=./.vault_pass.txt
      when: not vault_pass.stat.exists

## INIT EXAMPLE SERVER SPEC TEST CASE
    - name: Creates test directory
      file: path=tests/ansible-tdd/integration state=directory recurse=true

    - stat: path=./tests/ansible-tdd/integration/README.markdown
      register: readme_markdown
    - name: Create sample file playbook
      copy: content="All testcase create at here" dest=./tests/ansible-tdd/integration/README.markdown
      when: not readme_markdown.stat.exists

    - stat: path=./tests/default.yml
      register: role_test
    - name:  Create role_test
      template:
        src: "templates/serverspec/template-testcase/default_test_role.j2"
        dest: ./tests/default.yml
      when: not role_test.stat.exists
