---

- hosts: localhost
  connection: local
  vars:
    no_log: false
  pre_tasks:
    - include_vars: "{{ item }}"
      with_first_found:
        - "{{tdd_provisioning}}"
    - include_vars: "{{ item }}"
      with_first_found:
        - "templates/ec2_secret_access.yml"
    - include_vars: "{{ item }}"
      with_first_found:
        - "{{vault_ec2_secret_access}}"
  tasks:
    - file: path="./.log/{{provision.app_name}}" state=directory mode=0775
    - name: Start the sandbox instances
      ec2:
    ## required
        aws_access_key: '{{ aws_access_key_id }}'
        aws_secret_key: '{{ aws_secret_access_key }}'
        key_name: '{{ item.key_name }}'
        region: '{{ item.region }}'
        instance_tags: '{{ {"Name": "unknown","app_name": provision.app_name,"server_group":item.server_group}|combine(item.instance_tags|default({}))  }}'
        exact_count: '{{ item.num_instances }}'
        volumes: '{{ item.volumes|default([ { "device_name": "/dev/sda1", "volume_size": 8, "delete_on_termination": true }]) }}' 
    #more than usage
        
        instance_type: '{{ item.instance_type }}'
        image: '{{ item.image }}'
        assign_public_ip: '{{ item.assign_public_ip|default("yes") }}'
        group: '{{ item.group }}'
        vpc_subnet_id: '{{ item.vpc_subnet_id}}'
        wait: '{{ item.wait|default("yes") }}'

    ## less than usage        
        count_tag:
          app_name: "{{provision.app_name}}"
          server_group: "{{item.server_group}}"
        zone: '{{ item.zone}}'
        instance_profile_name: '{{ item.instance_profile_name|default("") }}'
        kernel: '{{ item.kernel|default("") }}'
        monitoring: '{{ item.monitoring|default("no") }}'
        placement_group: '{{ item.placement_group|default("") }}'
        private_ip: '{{ item.private_ip|default("") }}'
        profile: '{{ item.profile|default("") }}'
        ramdisk: '{{ item.ramdisk|default("") }}'
        wait_timeout: '{{ item.wait_timeout|default(300) }}'
        ec2_url: '{{ item.ec2_url|default("") }}'
        ebs_optimized: '{{ item.ebs_optimized|default("false") }}'

        security_token: '{{ item.security_token|default("") }}'
        source_dest_check: '{{ item.source_dest_check|default("True") }}'

        tenancy:  '{{ item.tenancy|default("default") }}'
        termination_protection: '{{ item.termination_protection|default("no") }}'
        user_data: '{{ item.user_data|default("") }}'
        validate_certs: '{{ item.validate_certs|default("yes") }}'
      register: ec2
      with_items:
        - "{{provision.servers}}"
      no_log: "{{no_log}}"

    - name: Add new instance to host group
      add_host: name="{{item.1.id}}" hostname="{{ item.1.public_ip }}" groupname="{{item.0.item.server_group}}" ansible_ssh_user="{{ item.0.item.ansible_ssh_user }}" ansible_port="{{ item.0.item.ansible_port }}" instances_id="{{item.1.id}}" public_ip="{{ item.1.public_ip }}" aws_region={{item.1.region}} private_ip={{item.1.private_ip}} ansible_ssh_private_key_file={{ansible_ssh_private_key_file|default("")}} ami_launch_index={{item.1.ami_launch_index}}
      when: item.1.tags.Name=='unknown'
      with_subelements:
        - ec2.results
        - tagged_instances
      no_log: "{{no_log}}"

    - name: Add new instance to host group
      add_host: name="{{item.1.tags.Name}}" hostname="{{ item.1.public_ip }}" groupname="{{item.0.item.server_group}}" ansible_ssh_user="{{ item.0.item.ansible_ssh_user }}" ansible_port="{{ item.0.item.ansible_port }}" instances_id="{{item.1.id}}" public_ip="{{ item.1.public_ip }}" aws_region={{item.1.region}} private_ip={{item.1.private_ip}} ansible_ssh_private_key_file={{ansible_ssh_private_key_file|default("")}} ami_launch_index={{item.1.ami_launch_index}}
      when: item.1.tags.Name!='unknown'
      with_subelements:
        - ec2.results
        - tagged_instances
      no_log: "{{no_log}}"

    - name: Generate skeleton-instance-name
      template:
        src: "templates/rename-instances/skeleton-instance-name.j2"
        dest: "./.log/{{provision.app_name}}/skeleton-instance-name.yml"
    - name: Generate real-instance-name
      template:
        src: "templates/rename-instances/real-instance-name.j2"
        dest: "./.log/{{provision.app_name}}/real-instance-name.yml"