require 'rake'
require 'rspec/core/rake_task'
require 'yaml'

task :spec    => 'spec:all'
task :default => :spec

namespace :spec do
  ENV['TESTCASE_NAME'] = nil
  suite_name = ENV['TESTCASE_NAME']
  ansible_tdd = YAML.load_file('ansible_tdd.yml')
  aws_inventory = YAML.load_file('ansible_tdd_inventory.yml')
  ansible_host = ''
  ansible_ssh_user = ''


  ansible_tdd["test-cases"].each do |name_test_cases , test_cases|
    if name_test_cases == suite_name or suite_name.nil?
      atdd_suite_path = "./tests/ansible-tdd/integration/#{name_test_cases}/spec/*"
      targets = []
      targets_belong_host = {}

      test_cases.each do |test_case|
        targets << test_case["spec"]
        targets_belong_host[test_case["spec"]] = test_case["host_group"];
      end

      task :all     => targets
      task :default => :all

      targets.each do |test_case_name|
        aws_inventory[targets_belong_host[test_case_name]].each do |group|
          ansible_host = group["ansible_host"]
          ansible_ssh_user = group["ansible_ssh_user"]

          desc "Run serverspec tests to #{test_case_name}"
          RSpec::Core::RakeTask.new(test_case_name) do |t|
            ENV['ATDD_TARGET_HOST'] = ansible_host
            ENV['ATDD_TARGET_SSH_USER'] = ansible_ssh_user
            t.pattern = "./tests/ansible-tdd/integration/#{name_test_cases}/spec/#{test_case_name}.rb"
          end
        end
      end

    end


  end
end

