---
#ansible playbook prepare mockup test

- hosts: localhost
  connection: local
  tasks:
    - debug: msg="#ansible playbook setup mockup test"
  post_tasks:
      - include: "{{ lookup('env','ATDD_SETUP_MOCKUP') }}"